### ISSUE TITLE
恢复老文章的图片和 caption

### ISSUE THREAD

**Issue by bojieli** [ustclug/news#3]
Example:
- http://news.ustclug.org/lug%E6%B4%BB%E5%8A%A8/2016/06/16/new-activity-room-in-west-library.html
- http://news.ustclug.org/lug%E4%BC%9A%E8%AE%AE/2013/04/29/lug.html

**Comment by SmartHypercube** [comment]
done

**Comment by zhsj** [comment]
能否避免使用第三方图片托管服务？直接把图片放到git repo中，虽然大了些，但可以保证以后不会丢失、链接不会变动。

**Comment by SmartHypercube** [comment]
把曾经 WordPress 的文件都放到了 https://ftp.ustclug.org/wp-content/ ，并改成了从这里提供图片。
话说把这些东西这样放在 FTP 里有什么值得注意的问题吗？
