### ISSUE TITLE
添加 RSS feed

### ISSUE THREAD

**Issue by katherlee** [ustclug/news#7]
可否添加 RSS feed 方便订阅？GitHub Pages 似乎直接支持 Jekyll plugins，所以应该只需要在`_config.yml` 里面添加
```yaml
plugins:
  - jekyll-paginate #Fix deprecation warning
  - jekyll-feed #Add feeds
```
即可在 build 的时候自动生成 `feed.xml`。

非常感谢！

**Comment by iBug** [comment]
是个不错的主意。我已经加上了 `jekyll-feed`，如果我没记错的话，`jekyll-paginate` 是默认启用的（而且不能禁用），无需额外指定。
